export const CAR_LIST: Car[] = [
  {
    id: 1,
    make: "Toyota",
    model: "Corolla",
    year: 2023,
    price: 25000,
    color: "Blue",
    mileage: 10000,
    transmission: "Automatic",
  },
  {
    id: 2,
    make: "Honda",
    model: "Civic",
    year: 2022,
    price: 23000,
    color: "Red",
    mileage: 15000,
    transmission: "Manual",
  },
  {
    id: 3,
    make: "Ford",
    model: "Mustang",
    year: 2024,
    price: 45000,
    color: "Black",
    mileage: 5000,
    transmission: "Automatic",
  },
  {
    id: 4,
    make: "Tesla",
    model: "Model 3",
    year: 2021,
    price: 38000,
    color: "White",
    mileage: 20000,
    transmission: "Electric",
  },
  {
    id: 5,
    make: "BMW",
    model: "3 Series",
    year: 2023,
    price: 42000,
    color: "Silver",
    mileage: 8000,
    transmission: "Automatic",
  },
  {
    id: 6,
    make: "Chevrolet",
    model: "Camaro",
    year: 2022,
    price: 35000,
    color: "Yellow",
    mileage: 12000,
    transmission: "Manual",
  },
  {
    id: 7,
    make: "Nissan",
    model: "Altima",
    year: 2023,
    price: 28000,
    color: "Gray",
    mileage: 9000,
    transmission: "Automatic",
  },
  {
    id: 8,
    make: "Hyundai",
    model: "Elantra",
    year: 2022,
    price: 24000,
    color: "Green",
    mileage: 14000,
    transmission: "Manual",
  },
  {
    id: 9,
    make: "Subaru",
    model: "Outback",
    year: 2024,
    price: 32000,
    color: "Blue",
    mileage: 7000,
    transmission: "Automatic",
  },
  {
    id: 10,
    make: "Kia",
    model: "Sorento",
    year: 2023,
    price: 30000,
    color: "Red",
    mileage: 11000,
    transmission: "Automatic",
  },
  {
    id: 11,
    make: "Mazda",
    model: "CX-5",
    year: 2022,
    price: 31000,
    color: "Black",
    mileage: 13000,
    transmission: "Automatic",
  },
  {
    id: 12,
    make: "Volkswagen",
    model: "Golf",
    year: 2023,
    price: 27000,
    color: "White",
    mileage: 10000,
    transmission: "Manual",
  },
  {
    id: 13,
    make: "Jeep",
    model: "Grand Cherokee",
    year: 2024,
    price: 40000,
    color: "Silver",
    mileage: 6000,
    transmission: "Automatic",
  },
  {
    id: 14,
    make: "Dodge",
    model: "Charger",
    year: 2023,
    price: 37000,
    color: "Yellow",
    mileage: 8000,
    transmission: "Automatic",
  },
  {
    id: 15,
    make: "Ram",
    model: "1500",
    year: 2024,
    price: 45000,
    color: "Gray",
    mileage: 5000,
    transmission: "Automatic",
  },
  {
    id: 16,
    make: "GMC",
    model: "Sierra",
    year: 2023,
    price: 42000,
    color: "Blue",
    mileage: 7000,
    transmission: "Automatic",
  },
  {
    id: 17,
    make: "Cadillac",
    model: "XT5",
    year: 2022,
    price: 48000,
    color: "Red",
    mileage: 12000,
    transmission: "Automatic",
  },
  {
    id: 18,
    make: "Lincoln",
    model: "Navigator",
    year: 2024,
    price: 60000,
    color: "Black",
    mileage: 3000,
    transmission: "Automatic",
  },
  {
    id: 19,
    make: "Lexus",
    model: "RX",
    year: 2023,
    price: 52000,
    color: "White",
    mileage: 9000,
    transmission: "Automatic",
  },
  {
    id: 20,
    make: "Infiniti",
    model: "QX50",
    year: 2022,
    price: 45000,
    color: "Silver",
    mileage: 11000,
    transmission: "Automatic",
  },
];
